/**
 * tools/test/property.mjs — AAA-26: seeded property-based testing (fast-check
 * style). Reproducible per seed, with shrinking to a minimal counterexample.
 *
 * Generators draw from a seeded RNG stream; each run derives its own seed from
 * a base seed + label + run index, so a failing run is reproducible. On a
 * violation we shrink the counterexample toward 0 (numeric bisection) while the
 * invariant still fails, returning the minimal failing input.
 */
import { RNG, DEFAULT_SEED } from '../../src/core/rng.js';

export function deriveRunSeed(base, label, run) {
  let h = base >>> 0;
  const s = `${label}::${run}`;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x9e3779b1) >>> 0;
    h ^= h >>> 13;
  }
  h ^= h >>> 17;
  return h >>> 0;
}

/** fast-check-style generators: (rng) => value */
export const gen = {
  int: (min, max) => (rng) => min + Math.floor(rng.float() * (max - min + 1)),
  float: (min = 0, max = 1) => (rng) => min + rng.float() * (max - min),
  bool: () => (rng) => rng.float() < 0.5,
  coord: (radius) => (rng) => gen.int(-radius, radius)(rng),
  pair: (ga, gb) => (rng) => [ga(rng), gb(rng)],
  tuple: (gs) => (rng) => gs.map(g => g(rng)),
  arrayOf: (g, len) => (rng) => Array.from({ length: len }, () => g(rng)),
};

/** Shrink a single numeric value toward 0 by repeated bisection. */
function shrinkNum(v) {
  const out = [];
  let c = Math.abs(v);
  while (c > 1) {
    c = Math.floor(c / 2);
    out.push((v < 0 ? -1 : 1) * c);
  }
  out.push(0);
  return [...new Set(out)];
}

/** Candidate counterexamples: shrink one numeric field at a time toward 0. */
function shrinkCandidates(input) {
  const out = [];
  if (typeof input === 'number') {
    for (const c of shrinkNum(input)) out.push([c]);
  } else if (Array.isArray(input)) {
    for (let i = 0; i < input.length; i++) {
      if (typeof input[i] === 'number') {
        for (const c of shrinkNum(input[i])) {
          const cand = input.slice();
          cand[i] = c;
          out.push(cand);
        }
      }
    }
  }
  return out;
}

function isSmaller(a, b) {
  const mag = (v) => typeof v === 'number' ? Math.abs(v) : Array.isArray(v) ? v.reduce((s, x) => s + Math.abs(x || 0), 0) : 0;
  return mag(a) < mag(b);
}

/**
 * Run `invariant` over `runs` seeded random inputs generated by `generator`.
 * Returns { pass, ... } with a shrunk minimal counterexample on failure.
 *
 *   forAll({ seed, generator, invariant, runs, label })
 *   - generator: (rng) => input
 *   - invariant: (input) => void  (throw to flag a violation)
 */
export function forAll({ seed = DEFAULT_SEED, generator, invariant, runs = 100, label = 'prop' }) {
  let fail = null;
  for (let run = 0; run < runs; run++) {
    const runSeed = deriveRunSeed(seed, label, run);
    const rng = new RNG(runSeed);
    const input = generator(rng);
    try {
      invariant(input);
    } catch (e) {
      fail = { run, runSeed, input, error: String((e && e.message) || e) };
      break;
    }
  }
  if (!fail) return { pass: true, runs, label, seed, seedBase: seed };

  // Shrink the failing counterexample toward a minimal one.
  let best = fail;
  let changed = true;
  while (changed) {
    changed = false;
    for (const cand of shrinkCandidates(best.input)) {
      try { invariant(cand); } catch (e) {
        if (isSmaller(cand, best.input)) {
          best = { ...best, input: cand, error: String((e && e.message) || e) };
          changed = true;
          break;
        }
      }
    }
  }

  return {
    pass: false, runs, label, seed,
    failingRun: best.run, runSeed: best.runSeed,
    counterexample: best.input, error: best.error,
  };
}
