import * as THREE from 'three';

/**
 * ConstructionSystem — animates active construction sites (tower cranes)
 * generated by world.js. Each site record holds the animated crane meshes
 * (pivot/jib/hook/cable). update() swings the jib and hoists the hook block
 * deterministically: phase advances by delta * SPEED every frame, so the
 * animation is reproducible for the verification harness.
 */
export class ConstructionSystem {
    constructor(scene) {
        this.scene = scene;
        this.sites = new Map(); // "cx,cz" -> [site records]
        this.cranes = [];       // flat list of animated records
        this.SPEED = 0.35;      // rad/s jib rotation
    }

    loadChunk(cx, cz, chunkData) {
        const sites = (chunkData && chunkData.construction) ? chunkData.construction : [];
        if (sites.length) {
            this.sites.set(`${cx},${cz}`, sites);
            for (const s of sites) this.cranes.push(s);
        }
    }

    unloadChunk(cx, cz) {
        const key = `${cx},${cz}`;
        const sites = this.sites.get(key);
        if (sites) {
            for (const s of sites) {
                const i = this.cranes.indexOf(s);
                if (i > -1) this.cranes.splice(i, 1);
            }
            this.sites.delete(key);
        }
    }

    update(delta) {
        for (const s of this.cranes) {
            s.phase += delta * this.SPEED;
            const ph = s.phase;
            s.pivot.rotation.y = ph;
            // hoist cycle: the hook block slides along the jib and hoists
            s.hook.position.x = s.jibLen * (0.5 + 0.5 * Math.sin(ph * 0.7));
            s.hook.position.y = -3 - 7 * Math.max(0, Math.sin(ph * 0.35));
            if (s.cable) {
                s.cable.position.y = s.hook.position.y / 2;
                s.cable.scale.y = Math.max(0.25, -s.hook.position.y);
            }
        }
    }

    craneCount() {
        return this.cranes.length;
    }
}
